name: CI

# run this pipeline every time someone pushes to the main branch.
on: 
  push:
    branches: [main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build the image
        run: docker build -t test:${{ github.sha }} ./lapp-docker